export const layoutTypes = {
  TOGGLE_DRAWER: "TOGGLE_DRAWER",
  SET_OPEN_DRAWER: "SET_OPEN_DRAWER",
  TOGGLE_LOADING_MAIN: "LOADING_MAIN",
  HIDE_BREADCRUMBS: "HIDE BREADCRUMBS",
  SHOW_BREADCRUMBS: "SHOW_BREADCRUMBS",
  TITLE: "TITLE",
  SUB_BREADCRUMBS: "SUB_BREADCRUMBS",
  SET_PARAMS: "SET_PARAMS",
  REFRESH_MENU: "REFRESH_MENU",
};
